# Generated by Django 4.0.1 on 2022-02-02 04:25

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_picturemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
