# Generated by Django 4.0.1 on 2022-02-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_picturemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturemodel',
            old_name='content',
            new_name='story',
        ),
    ]
