# Generated by Django 4.0.1 on 2022-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_content_picturemodel_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='story',
            field=models.TextField(),
        ),
    ]
