# Generated by Django 4.0.1 on 2022-02-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_verified',
            new_name='is_verified',
        ),
    ]
